name: 'Version Bump'
on:
  workflow_dispatch:
  pull_request:

jobs:
  files-changed:
    runs-on: ubuntu-latest
    outputs:
      embr_charts: ${{ steps.changes.outputs.embr_charts }}
      example_perspective_component: ${{ steps.changes.outputs.example_perspective_component }}
    steps:
      - uses: actions/checkout@v4

      - name: Check for file changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            example_perspective_component:
              - 'modules/example-perspective-component/**'
            embr_charts:
              - 'modules/embr-charts/**'


  embr-charts:
    if: needs.files-changed.outputs.embr_charts == 'true'
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: embr-charts

  example-perspective-component:
    if: needs.files-changed.outputs.example_perspective_component == 'true'
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: example-perspective-component
